#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Feb 18 11:26:24 2019

@author: jakerabinowitz
"""

#circuit of resistors 

#system of equations

#1. 4v1 -v2 - v3 - v4 = v
#2.-1v1 +3v2 +0v3 - v4 = 0
#3 -v1  +0v2 +3v3 - v4 = v
#4 -v1 - v2 - v3 +4v4 = 0 

