#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Jan 28 11:04:24 2019

@author: jakerabinowitz
"""

from numpy import cos, sin, pi, empty, exp
from pylab import imshow,show, colorbar, jet, hot, cool

points = 500
xmin = -2*pi
xmax = 2*pi

ymin = xmin
ymax = xmax


dx = (xmax - xmin)/points
dy = (ymax - ymin)/points

#generate a 2D array
z = empty([points, points], float)

for i in range(points):
    y = ymin + i*dy
    
    for j in range(points):
        x = xmin +j*dx
        
        z[i,j] = (sin(x))*cos(y)

imshow(z, origin = "lower")#turns graph into image and then make origen lower lef
jet()
colorbar()
show()