#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Feb 11 11:17:44 2019

@author: jakerabinowitz
"""

from numpy import sqrt, tanh, zeros, linspace
from pylab import show, plot, xlabel, ylabel

def f(x):
    return 1+.5*tanh(2*x)
    
  
    
N = 100
dfdx = zeros(N, float)
#derivative perameters

x = linspace(-2,2,N)
h = 1e-5

for i in range(0, N):
    dfdx[i] = ((f(x[i]+h/2) - f(x[i] - h/2))/h)

plot(x, dfdx, 'ro')
xlabel("x value")
ylabel("derivative")
show()
    