#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri Jan 25 11:36:41 2019

@author: jakerabinowitz
"""

from pylab import plot, show, xlabel, ylabel
from numpy import sin, cos, linspace

#x =[1.0, 2.4, 1.7, 3, 3.1, 6]
#y =[2, 3, 6, 1, 1, 1,]

x = linspace(0, 10, 100)
y = 0*x+pi/2
plot(x,y, "r") #o = circle, s = square, r = red
show()