#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri Jan 18 11:41:18 2019

@author: jakerabinowitz
"""

G = 6.67e-11
M = 5.97e24
R = 6.371e6

pi= 3.14159

for Thours in range(0,24,2) :
    T = 3600*Thours
    h = (G*M*T**2/(4*pi**2))**(1/3) - R
    
    if h < 0:
        print("Orbit not possible")
        
    else :
        print("Height of orbit is:", h, "meters when period is", Thours, "hours")