#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Feb  4 11:16:00 2019

@author: jakerabinowitz
"""
from numpy import e

def f(x):
    if x == 0:
        return 0
    else:
        return x**4-2*x+1


N = 10000
a = 0
b = 2
h = (b-a)/N
integral = 0
actual = 4.4

for k in range(1, N+1):
    A = .5*h*(f(a+(k-1)*h)+f(a+k*h))
    integral+= A

print(integral)

#100 slices
s100 = 4.401066656000001

#200
s200 = 4.400266666

error = (1/3)*(s200-s100)

print(error)



#print(("Percent difference: ", abs((actual - integral)/integral)*100))
