#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Feb 25 11:26:25 2019

@author: jakerabinowitz
"""
from numpy import tanh, cosh, arctanh
from pylab import plot, linspace, grid, show

def arctanNewton(u):
    x1 = 0.0
    delta = 1
    accuracy = 1e-12
    while delta > accuracy:
        x2 = x1 - (tanh(x1)-u)*cosh(x1)**2
        delta = abs(x2-x1)
        x1 = x2
    return x2

x = linspace(0,4,100)

upoints = linspace(-.99, .99, 50)
xpoints = []

for u in upoints:
    xpoints.append(arctanh(u))

print(xpoints)

plot(upoints, xpoints, 'r.')
grid()
show()
