#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri Feb 15 11:25:26 2019

@author: jakerabinowitz
"""

from solvematrix import solvematrix 
from numpy import array

M = array([[2,4,-6],
           [3,7,-10],
           [2,6,-7]],float)

v = array([8, 14, 13], float)

x = solvematrix(M,v)

print(x)