#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri Jan 25 11:10:06 2019

@author: jakerabinowitz
"""

def factorial(n):
    fac = 1
    for i in range (1, n+1):
        fac *= i
    return fac

num = 12

print(num, "! =", factorial(num))