#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Feb 27 11:14:17 2019

@author: jakerabinowitz
"""

from numpy import array, sqrt
from solvematrix import solvematrix 

def f(x,y):
    f1 = -x + a* y + x**2*y
    f2 = b - a*y - x**2*y
    return array([f1, f2], float)
    
def gradf(x,y):
    df1dx = -1 + 2*x*y    #xpartial of f1
    df1dy = a + x**2      #ypartial of f1
    df2dx = -2*x*y        #xpartial of f2
    df2dy = -a - x**2     #ypartial of f2
    
    return array([[df1dx, df1dy],
                  [df2dx, df2dy]], float)
    
#function parameters
a = 1.0
b = 2.0

#initial guesses
x = 0.5
y = 0.5
delta = array([1.0, 1.0], float)
accuracy = 1e-6

while sqrt(delta[0]**2+delta[1]**2) > accuracy:
    delta = solvematrix(gradf(x, y), f(x,y))
    x -= delta[0]
    y -= delta[1]

print("x = ", x, "y = ", y)
