#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri Feb 15 11:37:43 2019

@author: jakerabinowitz
"""

from solvematrix import silvematrix
from numpy import array, zeros, loadtxt

data = loadtxt("data.txt", float)
x = data[:,0]
y = data[:,1]
N = len(x) #number of data points

#fit parameters 
degree = 4
A = zeros([degree+1, degree+1], float)
v = zeros()


for i in range(len(x)):
    for j in range(len(x)):
        A[i,j] = sum(x**(i+j))

