#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Feb 21 19:52:32 2019

@author: jakerabinowitz
"""

#Pset 4 question 5
from numpy import array
from solvematrix import solvematrix

g = 9.8  
N = 4 #number of equations

#2D array to set the value of the masses
Mass = array([[2,5,1],
              [2,2,2],
              [4,4,4],
              [0,5,1],
              [2,5,0]], float)

for i in range(N+1):
    #looping through all the masses
    mass1 = Mass[i, 0]
    mass2 = Mass[i, 1]
    mass3 = Mass[i, 2]
    #The A matrix for the system Ax=b
    A = array([[mass1, 0, 0, -1], 
               [0, mass2, 0, -1],
               [0, 0, mass3, 2],
               [-1, -1, +2, 0]])
    #The b vector for the system Ax=b
    b = array([0,0,mass3*g,0], float)
    #The x vector for the system Ax=b
    x = solvematrix(A, b) 
    
    #printing the outcomes
    print("Mass1 =", mass1, "Mass2 =", mass2, "Mass3 =", mass3)
    print("acceleration1 =",x[0], "acceleration2 =", x[1], "acceleration3 =",x[2])
    print("tension =",x[3])
    print()



