#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Feb 25 22:12:01 2019

@author: jakerabinowitz
"""

#Pset 5 Q3

from pylab import show, plot, grid, linspace

def L1(r):
    return G*Me/(r**2) - G*Mm/(R-r)**2 - r*w**2 

def L2(r):
    return G*Me/(r**2) + G*Mm/(R-r)**2 - r*w**2 

def L3(r):
    return G*Me/(r**2) + G*Mm/(R-r)**2 + r*w**2 

#Constants
R = 3.844e8     #distance from Earth to Moon
Me = 5.974e24   #mass of Earth
Mm =7.348e22    #mass of Moon
G = 6.674e-11   #gravitational constant
w = 2.662e-6    #angular velocity
r = 0

#Secant law perameters

delta = 1.0
accuracy = 1e-4
    
#Secand for L1(r)
x1 = 0.1*R
x2 = 0.999*R
while abs(delta) > accuracy:
        delta = L1(x2)*(x2 - x1)/(L1(x2) - L1(x1))
        x1 = x2
        x2 -= delta

print("L1 = " , int(x2), "meters")

#Secand for L2(r)
x1 = 0.1*R
x2 = 0.999*R
delta = 1.0
while abs(delta) > accuracy:
        delta = L2(x2)*(x2 - x1)/(L2(x2) - L2(x1))
        x1 = x2
        x2 -= delta

print("L2 = " , int(x2), "meters")

#Secand for L3(r)
x1 = -0.1*R
x2 = -0.999*R
delta = 1.0
while abs(delta) > accuracy:
        delta = L3(x2)*(x2 - x1)/(L3(x2) - L3(x1))
        x1 = x2
        x2 -= delta

print("L3 = " , int(x2), "meters")

"""
x = linspace(0.1*R, 0.99*R, 1000)
plot(x, L1(x), 'g')
grid()
show()
"""