#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri Jan 25 11:31:50 2019

@author: jakerabinowitz
"""

def vector(x, y, z):
   
    
    length =(x**2 + y**2 + z**2)**.5
    return length

print(vector(2, 10, 2))
    